# Google Cloud Run Configuration
# Deploy using: gcloud run deploy suryादrishti --source .

# Cloud Run automatically detects Dockerfile
# Set these environment variables in Cloud Run console or via gcloud:

# gcloud run services update suryादrishti \
#   --set-env-vars="DATABASE_URL=postgresql://..." \
#   --set-env-vars="REDIS_URL=redis://..." \
#   --set-env-vars="SECRET_KEY=..." \
#   --set-env-vars="DEBUG=False"

# Or use Cloud Run YAML:
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: suryादrishti
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/suryादrishti:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: suryादrishti-secrets
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-url
              name: suryादrishti-secrets
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: suryादrishti-secrets
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8000

